# Generated by Django 3.0.6 on 2020-08-26 20:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='thumbnails')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('body_text', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('course_hour', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
