# Generated by Django 3.0.6 on 2020-09-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freepdf', '0002_pdf_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'ordering': ['-pk']},
        ),
    ]
